(cl:in-package RelocSensorDriver-msg)
(cl:export '(HEADER-VAL
          HEADER
          US1-VAL
          US1
          US2-VAL
          US2
          US3-VAL
          US3
          US4-VAL
          US4
          USID-VAL
          USID
          IRX1-VAL
          IRX1
          IRY1-VAL
          IRY1
          IRX2-VAL
          IRX2
          IRY2-VAL
          IRY2
          IRX3-VAL
          IRX3
          IRY3-VAL
          IRY3
          IRX4-VAL
          IRX4
          IRY4-VAL
          IRY4
          IRID-VAL
          IRID
))